/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3ECHARTBOOST_AUTODEFS_H
#define S3ECHARTBOOST_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_CHARTBOOST_NAME "s3eChartboost"
#define S3E_EXT_CHARTBOOST_HASH 0x37830649

#endif /* !S3ECHARTBOOST_AUTODEFS_H */
