/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "s3eChartboost.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       void(*s3eChartboostSetAppID_t)(const char* id);
typedef       void(*s3eChartboostSetAppSignature_t)(const char* signature);
typedef       void(*s3eChartboostInstall_t)();
typedef       void(*s3eChartboostCacheInterstitial_t)(const char* name);
typedef       void(*s3eChartboostShowInterstitial_t)(const char* name);
typedef       void(*s3eChartboostCacheMoreApps_t)();
typedef       void(*s3eChartboostShowMoreApps_t)();

/**
 * struct that gets filled in by s3eChartboostRegister
 */
typedef struct s3eChartboostFuncs
{
    s3eChartboostSetAppID_t m_s3eChartboostSetAppID;
    s3eChartboostSetAppSignature_t m_s3eChartboostSetAppSignature;
    s3eChartboostInstall_t m_s3eChartboostInstall;
    s3eChartboostCacheInterstitial_t m_s3eChartboostCacheInterstitial;
    s3eChartboostShowInterstitial_t m_s3eChartboostShowInterstitial;
    s3eChartboostCacheMoreApps_t m_s3eChartboostCacheMoreApps;
    s3eChartboostShowMoreApps_t m_s3eChartboostShowMoreApps;
} s3eChartboostFuncs;

static s3eChartboostFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x37830649, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: s3eChartboost");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x37830649, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eChartboostAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

void s3eChartboostSetAppID(const char* id)
{
    IwTrace(CHARTBOOST_VERBOSE, ("calling s3eChartboost[0] func: s3eChartboostSetAppID"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eChartboostSetAppID(id);
}

void s3eChartboostSetAppSignature(const char* signature)
{
    IwTrace(CHARTBOOST_VERBOSE, ("calling s3eChartboost[1] func: s3eChartboostSetAppSignature"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eChartboostSetAppSignature(signature);
}

void s3eChartboostInstall()
{
    IwTrace(CHARTBOOST_VERBOSE, ("calling s3eChartboost[2] func: s3eChartboostInstall"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eChartboostInstall();
}

void s3eChartboostCacheInterstitial(const char* name)
{
    IwTrace(CHARTBOOST_VERBOSE, ("calling s3eChartboost[3] func: s3eChartboostCacheInterstitial"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eChartboostCacheInterstitial(name);
}

void s3eChartboostShowInterstitial(const char* name)
{
    IwTrace(CHARTBOOST_VERBOSE, ("calling s3eChartboost[4] func: s3eChartboostShowInterstitial"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eChartboostShowInterstitial(name);
}

void s3eChartboostCacheMoreApps()
{
    IwTrace(CHARTBOOST_VERBOSE, ("calling s3eChartboost[5] func: s3eChartboostCacheMoreApps"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eChartboostCacheMoreApps();
}

void s3eChartboostShowMoreApps()
{
    IwTrace(CHARTBOOST_VERBOSE, ("calling s3eChartboost[6] func: s3eChartboostShowMoreApps"));

    if (!_extLoad())
        return;

    g_Ext.m_s3eChartboostShowMoreApps();
}
